version: '3.8'

services:
  myapp:
    image: myapp:1
    ports:
      - "8080:5000"
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:17.5
    container_name: postgres_db
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - postgres_user
      - postgres_db
      - postgres_password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

secrets:
  postgres_user:
    external: true
  postgres_db:
    external: true
  postgres_password:
    external: true
